# Zappa equivalent of the default app generated by Express.
# See `express.coffee` for comparison.

@app = require('../src/zappa').run ->
  configure ->
    set views: "#{__dirname}/views", 'view engine': 'jade'
    app.register '.jade', zappa.adapter 'jade'
    use 'bodyParser', 'methodOverride', app.router, 'static'

  configure
    development: -> use errorHandler: {dumpExceptions: on, showStack: on}
    production: -> use 'errorHandler'

  get '/': ->
    @title = 'zappa'
    render 'index'