# Zappa equivalent of the default app generated by Express.
# See `express.coffee` for comparison.

@app = require('zappa') ->
  @configure ->
    @set 'view engine': 'jade'
    @register '.jade', @zappa.adapter 'jade'
    @use 'bodyParser', 'methodOverride', @app.router, 'static'

  @configure
    development: => @use errorHandler: {dumpExceptions: on, showStack: on}
    production: => @use 'errorHandler'

  @get '/': ->
    @data.title = 'zappa'
    @render 'index'
