# Zappa equivalent of the default app generated by Express.
# See `express.coffee` for comparison.

@app = require('../src/zappa') ->
  @configure =>
    @set 'view engine': 'jade'
    @use 'bodyParser', 'methodOverride', @app.router, 'static'

  @configure
    development: => @use errorHandler: {dumpExceptions: on, showStack: on}
    production: => @use 'errorHandler'

  @get '/': ->
    @render 'index', title: 'zappa'